version: "3.8"

services:

  notification-service:
    image: openjdk:17-jdk-alpine
    container_name: notificationservice
    ports:
      - 8080:8080
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - notificationdb
    networks:
      - my-net
    volumes:
      - ./build/libs/wot-project-2024-2025-NotificationService-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  notificationdb:
    image: mongo:5.0
    container_name: notificationDB
    ports:
      - 27017:27017
    networks:
      - my-net
networks:
  my-net:
    driver: "bridge"